Templates skip lib check (#7604)
Some failure is currently blocking CI 


```
packages/compiler test:e2e: node_modules/vscode-jsonrpc/lib/common/linkedMap.d.ts(28,5): error TS2416: Property 'forEach' in type 'LinkedMap<K, V>' is not assignable to the same property in base type 'Map<K, V>'.
packages/compiler test:e2e:   Type '(callbackfn: (value: V, key: K, map: LinkedMap<K, V>) => void, thisArg?: any) => void' is not assignable to type '(callbackfn: (value: V, key: K, map: Map<K, V>) => void, thisArg?: any) => void'.
packages/compiler test:e2e:     Types of parameters 'callbackfn' and 'callbackfn' are incompatible.
packages/compiler test:e2e:       Types of parameters 'map' and 'map' are incompatible.
packages/compiler test:e2e:         Type 'LinkedMap<K, V>' is not assignable to type 'Map<K, V>'.
packages/compiler test:e2e:           The types returned by 'entries()' are incompatible between these types.
packages/compiler test:e2e:             Property '[Symbol.dispose]' is missing in type 'IterableIterator<[K, V]>' but required in type 'MapIterator<[K, V]>'.
packages/compiler test:e2e: node_modules/vscode-jsonrpc/lib/common/linkedMap.d.ts(29,5): error TS2416: Property 'keys' in type 'LinkedMap<K, V>' is not assignable to the same property in base type 'Map<K, V>'.
packages/compiler test:e2e:   Type '() => IterableIterator<K>' is not assignable to type '() => MapIterator<K>'.
packages/compiler test:e2e:     Property '[Symbol.dispose]' is missing in type 'IterableIterator<K>' but required in type 'MapIterator<K>'.
packages/compiler test:e2e: node_modules/vscode-jsonrpc/lib/common/linkedMap.d.ts(30,5): error TS2416: Property 'values' in type 'LinkedMap<K, V>' is not assignable to the same property in base type 'Map<K, V>'.
packages/compiler test:e2e:   Type '() => IterableIterator<V>' is not assignable to type '() => MapIterator<V>'.
packages/compiler test:e2e:     Property '[Symbol.dispose]' is missing in type 'IterableIterator<V>' but required in type 'MapIterator<V>'.
packages/compiler test:e2e: node_modules/vscode-jsonrpc/lib/common/linkedMap.d.ts(31,5): error TS2416: Property 'entries' in type 'LinkedMap<K, V>' is not assignable to the same property in base type 'Map<K, V>'.
packages/compiler test:e2e:   Type '() => IterableIterator<[K, V]>' is not assignable to type '() => MapIterator<[K, V]>'.
packages/compiler test:e2e:     Property '[Symbol.dispose]' is missing in type 'IterableIterator<[K, V]>' but required in type 'MapIterator<[K, V]>'.
packages/compiler test:e2e: node_modules/vscode-jsonrpc/lib/common/linkedMap.d.ts(32,5): error TS2416: Property '[Symbol.iterator]' in type 'LinkedMap<K, V>' is not assignable to the same property in base type 'Map<K, V>'.
packages/compiler test:e2e:   Type '() => IterableIterator<[K, V]>' is not assignable to type '() => MapIterator<[K, V]>'.
packages/compiler test:e2e:     Property '[Symbol.dispose]' is missing in type 'IterableIterator<[K, V]>' but required in type 'MapIterator<[K, V]>'.

```

probably good to enable that anyway